USE NORTHWIND
SELECT * FROM Funcionarios

SELECT F1.NOME, F1.DataAdmissao, F2.Nome, F2.DataAdmissao
FROM Funcionarios F1, Funcionarios F2
WHERE DATEPART(YEAR, F1.DataAdmissao) = DATEPART(YEAR,F2.DataAdmissao)

USE AdventureWorks2012
-- MOSTRAR A MEDIA MENSAL DE VALORES VENDIDOS
-- SALES.SALESORDERHEADER

SELECT * FROM Sales.SalesOrderHeader

SELECT AVG(TotalDue), DATEPART(MONTH, OrderDate) MÊS 
FROM Sales.SalesOrderHeader
GROUP BY DATEPART(MONTH, OrderDate)
ORDER BY 2

SELECT AVG(TotalDue), DATEPART(YEAR, OrderDate) ANO 
FROM Sales.SalesOrderHeader
GROUP BY DATEPART(YEAR, OrderDate)
ORDER BY 2 ASC

-- QUAIS OS PRODUTOS ESTÃO ACIMA DA MEDIA DE VENDAS
-- PRODUCTION.PRODUCT - ID,LISTPRICE
-- SUB SELECT - PRODUCTION.PRODUCT


